version: "3"

services:
  jenkins:
    image: jc21/jenkins-node:latest
    ports:
      - 2222:22
    environment:
      - PUID=1000
      - PGID=1000
      - JENKINS_DATA=/var/lib/jenkins-node
    volumes:
      # This is required for docker control
      - '/var/run/docker.sock:/var/run/docker.sock'
      # This mount should be the same inside and out
      # and should be the same as JENKINS_DATA
      - '/var/lib/jenkins-node:/var/lib/jenkins-node'

volumes:
  jenkins_data:
