version: "3"

services:
  jenkins:
    image: jc21/jenkins-node:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - 'jenkins_data:/jenkins'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  jenkins_data:
