#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${DIR}/.."

. "${DIR}/../docker/rootfs/usr/bin/common.sh"

log_info "Building docker multiarch: ${YELLOW}${*}"

# Buildx Builder
docker buildx create --name "${BUILDX_NAME:-jenkins-node}" || echo
docker buildx use "${BUILDX_NAME:-jenkins-node}"
docker buildx build \
	--platform linux/amd64,linux/arm64,linux/arm/7 \
	--progress plain \
	--pull \
	-f docker/Dockerfile \
	$@ \
	.

docker buildx rm "${BUILDX_NAME:-jenkins-node}"
log_info 'Multiarch build Complete'
