#!/bin/bash -e

CYAN='\E[1;36m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
GREEN='\E[1;32m'
RESET='\E[0m'

TARGETPLATFORM=${1:unspecified}

# Determine the correct binary file for the architecture given
case $TARGETPLATFORM in
	linux/arm64)
		RPM=https://download.oracle.com/java/20/latest/jdk-20_linux-aarch64_bin.rpm
		;;

	linux/arm/v7)
		RPM=
		;;

	*)
		RPM=https://download.oracle.com/java/20/latest/jdk-20_linux-x64_bin.rpm
		;;
esac

if ! [ "${RPM:-}" = "" ]; then
	echo -e "${BLUE}❯ ${CYAN}Installing java from ${RPM} for ${YELLOW}${TARGETPLATFORM}${RESET}"
	curl -L "$RPM" -o /tmp/java.rpm
	yum -y localinstall /tmp/java.rpm
	rm -f /tmp/java.rpm
else
	# fall back to openjdk
	echo -e "${BLUE}❯ ${CYAN}Installing java from java-1.8.0-openjdk for ${YELLOW}${TARGETPLATFORM}${RESET}"
	yum -y install java-1.8.0-openjdk
fi

java -version
echo -e "${BLUE}❯ ${GREEN}java install Complete${RESET}"
