#!/bin/bash -e

. /usr/bin/common.sh

TARGETPLATFORM=${1:-unspecified}

# Determine the correct binary file for the architecture given
case $TARGETPLATFORM in
	linux/arm64)
		RPM=https://download.oracle.com/java/20/latest/jdk-20_linux-aarch64_bin.rpm
		;;

	linux/arm/v7)
		RPM=
		;;

	*)
		RPM=https://download.oracle.com/java/20/latest/jdk-20_linux-x64_bin.rpm
		;;
esac

if ! [ "${RPM:-}" = "" ]; then
	log_info "Installing java from ${RPM} for ${YELLOW}${TARGETPLATFORM}"
	curl -L "$RPM" -o /tmp/java.rpm
	yum -y localinstall /tmp/java.rpm
	rm -f /tmp/java.rpm
else
	# fall back to openjdk
	log_info "Installing java from java-1.8.0-openjdk for ${YELLOW}${TARGETPLATFORM}"
	yum -y install java-1.8.0-openjdk
fi

java -version
log_info "java install Complete"
