#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

mkdir -p /jenkins/data
chown -R "${PUID}:${PGID}" /jenkins /home/jenkins

#groupmod -g 1000 users || exit 1
useradd -u "${PUID}" -U -d /home/jenkins -s /bin/bash jenkins || exit 1
usermod -G jenkins jenkins || exit 1
groupmod -o -g "$PGID" jenkins || exit 1

echo "-------------------------------------
User UID: $(id -u jenkins)
User GID: $(id -g jenkins)
-------------------------------------
"
