#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

mkdir -p "${JENKINS_DATA:-/var/jenkins}"
chown -R "${PUID}:${PGID}" "${JENKINS_DATA:-/var/jenkins}" /home/jenkins

#groupmod -g 1000 users || exit 1
useradd -u "${PUID}" -U -d /home/jenkins -s /bin/bash jenkins || exit 1
usermod -G jenkins jenkins || exit 1
groupmod -o -g "$PGID" jenkins || exit 1

# is this even required?
usermod -aG docker jenkins

echo "-------------------------------------
User UID: $(id -u jenkins)
User GID: $(id -g jenkins)
-------------------------------------
"
